version: '3'

services:
 app1:
   build:
     context: ./app
   container_name: app1
   restart: always
   logging:
     driver: json-file
     options:
       max-size: "10m"
       max-file: "3"
   deploy:
     resources:
       limits:
         cpus: '0.4'  # 1/3 CPU
         memory: '1400M' # 1 GB

 app2:
   build:
     context: ./app
   container_name: app2
   restart: always
   logging:
     driver: json-file
     options:
       max-size: "10m"
       max-file: "3"
   deploy:
     resources:
       limits:
         cpus: '0.4'  # 1/3 CPU
         memory: '1400M' # 1 GB

 nginx:
   build:
     context: ./nginx
   container_name: nginx
   restart: always
   ports:
     - "8080:80"
   depends_on:
     - app1
     - app2
   logging:
     driver: json-file
     options:
       max-size: "10m"
       max-file: "3"
   deploy:
     resources:
       limits:
         cpus: '0.2'  # 1/3 CPU
         memory: '200M' # 1 GB
